version: '3.8'

services:
  # HLOC-NeRFStudio with RTX 5090 optimized environment
  # PyTorch 2.7.0 stable + CUDA 12.8 + sm_120 architecture support
  hloc-nerfstudio:
    image: hloc-nerfstudio:latest
    container_name: hloc-nerfstudio
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./data:/workspace/data:rw
      - ./outputs:/workspace/outputs:rw
      - ./models:/workspace/models:rw
    ports:
      - "7007:7007"
    stdin_open: true
    tty: true
    shm_size: '16gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]